### ISSUE TITLE
Lord Protector's Retainer v1.1 is triggering from stealth, when it shouldn't

### ISSUE THREAD

**Issue by Patane97** [throneteki-playtesting/throneteki#196]
Lord Protector's Retainer is redirecting stealth to itself apparently. I have not investigated this, but it doesn't seem too far-fetched as this sort of ability isn't seen/used often.

Need to investigate and, if a bug, fix it.

**Comment by ystros** [comment]
Just tested it, was not prompted when a Lord was chosen for stealth. Double checked the code and we never raise the onTargetsChosen for stealth. Don't think this is an issue.

![Image](https://user-images.githubusercontent.com/145077/190552452-62c4c019-12d3-4821-b2c7-8df12b31f7dd.png)
