### ISSUE TITLE
Some cards are showing targets within interrupt window, before a "reveal" effect

### ISSUE THREAD

**Issue by Patane97** [throneteki-playtesting/throneteki#203]
Cards, such as **A Traitor's Whisper** and **Littlefinger (AHaH)** are revealing the chosen "targets" to each opponent in the Interrupt window, which sort of "reveals" the cards before they've actually been revealed (and more importantly, before the event is potentially cancelled). 

~~This has been tested with similarly structured cards such as **Starfall Spy**, and it does not reveal the "chosen" card in shadows (as both ATW and SS just reference "a card" in shadows).~~
Edit: **Starfall Spy** *should* be showing the card, as you need to prove that you have chosen a card which can enter play (eg. not an event). **A Traitor's Whisper** *should not* be showing the card in the interrupt window as there is no criteria to the chosen cards, and any card of any criteria can be revealed (which cannot be said about "put into play").

See discord conversation for more details: https://discord.com/channels/698308957822779462/1004517884199981167/1020633481576976454

**Comment by EvadLhorg** [comment]
My quick test says that Starfall Spy does reveal the chosen card in the interrupt window when it triggers. It behaves the same way as a traitors whisper.
i suppose we need to fix all the cards then, or rather the whole interrupt referencing cards from facedown locations

**Comment by EvadLhorg** [comment]
Ok i think i figured out why it is still showing the card:
In the client, take a look at AbilityTargeting.jsx and the renderSimpleCard() method. It checks for card.facedown and then renders a cardback if it is true.
Then, in the backend, take a look at basecard.js and the getShortSummary() method: the property facedown is missing from the return value. But adding facedown: this.facedown doesn´t work, as cards in shadow are not facedown for the activePlayer.
I think instead you would have to copy over the 
if(!this.game.isCardVisible(this, activePlayer)) {
            return { facedown: true, uuid: this.uuid, tokens: this.tokens, ...selectionState };
        }
part from the getSummary function and figure out where and how to pass in the activePlayer variable.
