### ISSUE TITLE
Dragonstone reducing multiple events if leaving & entering play

### ISSUE THREAD

**Issue by Patane97** [throneteki-playtesting/throneteki#343]
Reports during the playtesting tournament that **Dragonstone** would reduce an event, leave play (eg. return to shadows via it's effect) then re-enter play. After this, it would reduce an ***additional*** event, when apparently it shouldn't.

**For Reference:**
![image](https://user-images.githubusercontent.com/23492047/224607770-8009ce16-ec19-4bf3-8659-4cc840ed6db7.png)

**Comment by ystros** [comment]
This would also be a problem with this effect (e.g. on Paxter) where if they played an event before Dragonstone entered play, it would reduce the next event played even though it isn't the "first."

**Comment by Patane97** [comment]
Card has changed; no longer has this ability.
